### ISSUE TITLE
Crashes on missing stats(?)

### ISSUE THREAD

**Issue by christoe** [jippi/hashi-ui#163]
Hashi-UI crashes on our cluster, after one glance on the code, seemingly because some machine stats is missing:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x413c5a]

goroutine 15 [running]:
panic(0xc7a9a0, 0xc42000a040)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
main.worker(0xc42049b230)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad_cluster_statistics.go:61 +0x33a
created by main.(*Nomad).collectAggregateClusterStatistics
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad_cluster_statistics.go:92 +0x1cc
```

Running Nomad 0.5.0. Works on "iverberk/nomad-ui:latest".

**Comment by jippi** [comment]
fixed :)
