### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by Theraga** [jippi/hashi-ui#213]
I am not sure what causes it but whenever I put a large number of jobs into Nomad (200+) or I try to Garbage clean nomad the webUI seems to crash. Is there anything I can do to stop it from crashing? I have added the full log below
```
panic: concurrent write to websocket connection

goroutine 77 [running]:
panic(0xc3b380, 0xc420254c50)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket.(*Conn).flushFrame(0xc4201c0000, 0xc420254c01, 0xc420254c29, 0x0, 0x7, 0x0, 0x10)
        /home/travis/gopath/src/github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket/conn.go:504 +0x45e
github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket.(*Conn).WriteMessage(0xc4201c0000, 0x9, 0xc420254c20, 0x9, 0x10, 0x10, 0x0)
        /home/travis/gopath/src/github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket/conn.go:642 +0x13b
main.(*NomadConnection).keepAlive(0xc420227aa0)
        /home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad_connection.go:302 +0x1d9
created by main.(*NomadConnection).Handle
        /home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad_connection.go:280 +0x43```

**Comment by taharah** [comment]
I ran into the same issue when attempting to use it with a large Consul installation (~10K services spread across 600 nodes). I'm not sure if it's trying to call out to the web because the nodes are behind 2 layers of firewalls so no direct internet connection. 
```go
01:09:49.116 consul_connection.go:64 ▶ INFO  [bbc60139] Started watching consul/node/<FQDN>
01:09:59.178 consul_connection.go:58 ▶ ERROR  [bbc60139] Could not write action to websocket: websocket: write closed
panic: concurrent write to websocket connection

goroutine 85 [running]:
panic(0xc3b380, 0xc4200f7f20)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket.(*Conn).flushFrame(0xc421a08000, 0xc4200f7f01, 0xc4200f7f19, 0x0, 0x7, 0x0, 0x10)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket/conn.go:504 +0x45e
github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket.(*Conn).WriteMessage(0xc421a08000, 0x9, 0xc4200f7f10, 0x9, 0x10, 0x10, 0x0)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/vendor/github.com/gorilla/websocket/conn.go:642 +0x13b
main.(*ConsulConnection).keepAlive(0xc42264a240)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/consul_connection.go:216 +0x1d9
created by main.(*ConsulConnection).Handle
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/consul_connection.go:194 +0x43
==> Caught signal: broken pipe
==> Caught signal: broken pipe
```

**Comment by jippi** [comment]
Fixed in https://github.com/jippi/hashi-ui/releases/tag/v0.13.4
