### ISSUE TITLE
Backend Crashes with `panic: send on closed channel`

### ISSUE THREAD

**Issue by cross311** [jippi/hashi-ui#263]
Have seen the backend crash many times with the same error message:

```
panic: send on closed channel

goroutine 219846 [running]:
main.(*NomadConnection).keepAlive(0xc4202e8660)
	/go/src/nomad-ui/backend/nomad_connection.go:300 +0x241
created by main.(*NomadConnection).Handle
	/go/src/nomad-ui/backend/nomad_connection.go:280 +0x43
```

**Comment by cross311** [comment]
Above that error message I see this:
```
[31m19:36:18.337 nomad_connection.go:77 ▶ ERROR [0m [20241c09] Could not write action to websocket: write tcp 172.17.0.34:3000->10.135.4.100:49620: write: connection reset by peer
[31m19:36:18.337 nomad_connection.go:77 ▶ ERROR [0m [20241c09] Could not write action to websocket: write tcp 172.17.0.34:3000->10.135.4.100:49620: write: connection reset by peer
[31m19:36:18.337 nomad_connection.go:77 ▶ ERROR [0m [20241c09] Could not write action to websocket: write tcp 172.17.0.34:3000->10.135.4.100:49620: write: connection reset by peer
[31m19:36:18.337 nomad_connection.go:77 ▶ ERROR [0m [20241c09] Could not write action to websocket: write tcp 172.17.0.34:3000->10.135.4.100:49620: write: connection reset by peer
[31m19:36:18.337 nomad_connection.go:77 ▶ ERROR [0m [20241c09] Could not write action to websocket: write tcp 172.17.0.34:3000->10.135.4.100:49620: write: connection reset by peer
[31m19:36:18.337 nomad_connection.go:77 ▶ ERROR [0m [20241c09] Could not write action to websocket: write tcp 172.17.0.34:3000->10.135.4.100:49620: write: connection reset by peer
[33m19:36:18.337 nomad_connection.go:71 ▶ WARNI [0m [20241c09] Stopping writePump
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching allocsShallow
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching nodes
19:36:18.337 nomad_connection.go:83 ▶ INFO [0m [20241c09] Stopped watching allocsShallow
```

**Comment by jippi** [comment]
Fixed by #264

**Comment by cross311** [comment]
@jippi We survived for a bit, but we still got the same issue with my fix.  Do you mind re-openning this as a bug.  I will take a look at it, since it is causing our nomad ui to restart around 3 times a day.  I am thinking it is more of a race condition.

**Comment by jippi** [comment]
Alright, please paste a full trace output from one of these crashes, then I can debug it :)

**Comment by cross311** [comment]
@jippi in the task is the trace that we get in the logs.  Is there more that you need?

**Comment by jippi** [comment]
there should be other go-routines running, need their traces too :)

**Comment by jippi** [comment]
Closing from lack of feedback, please try the latest version to see if it has fixed anything :)
