### ISSUE TITLE
Crash on viewing allocation

### ISSUE THREAD

**Issue by clinta** [jippi/hashi-ui#358]
Not all allocations, I only have one job that triggers this, but I'm not sure what about it is special.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bcbe7]

goroutine 553317 [running]:
github.com/jippi/hashi-ui/backend/vendor/github.com/hashicorp/consul/api.(*Client).newRequest(0x0, 0xacef32, 0x3, 0xc4201f2ae0, 0x19, 0xc4201f2ae0)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/vendor/github.com/hashicorp/consul/api/api.go:625 +0xb7
github.com/jippi/hashi-ui/backend/vendor/github.com/hashicorp/consul/api.(*Health).Node(0xc4208afd38, 0xc420170e70, 0x9, 0xc420348000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/vendor/github.com/hashicorp/consul/api/health.go:103 +0xec
github.com/jippi/hashi-ui/backend/nomad/allocations.(*health).Do(0xc420348070, 0xad7af9, 0x11, 0xc4203b1e78)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/nomad/allocations/health.go:57 +0x8d
github.com/jippi/hashi-ui/backend/subscriber.Watch.func2(0xc420308060, 0xc420308660, 0xc42021c7d0, 0xc42079c070, 0x63, 0xdf80a0, 0xc420348070, 0xc420812f60, 0xdf69e0, 0xc42021c820)
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/subscriber/functions.go:57 +0x1f4
created by github.com/jippi/hashi-ui/backend/subscriber.Watch
	/home/travis/gopath/src/github.com/jippi/hashi-ui/backend/subscriber/functions.go:48 +0x259

```

**Comment by jippi** [comment]
Hi, do this still happen in master?

**Comment by jippi** [comment]
Found the bug :D
